name: CI and automated releases
on:
  pull_request:
  push:
    branches: [ main, 'gh-readonly-queue/main/**' ]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-lib-ci.yml@main

  integration:
    runs-on: ubuntu-latest
    needs: ci
    name: "Test GitHub integration"
    permissions:
      id-token: write
    steps:
      - name: Debug OIDC Env Vars
        run: env
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: npm ci
        uses: nick-fields/retry@v2
        with:
          command: npm ci
          timeout_minutes: 3
          max_attempts: 3
        timeout-minutes: 5
      - run: npm run test:integration:github
        timeout-minutes: 5

  release:
    needs: integration
    permissions:
      id-token: write
      pages: write
      contents: write  # To create a Git tag
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-lib-release.yml@main
    with:
      api_docs: true
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
